FEED_CHANNEL_ID = -1002116317885
FEED_CHAT_ID = -1002050251720

GET_REFUND_CALLBACK = 'GET_REFUND_CALLBACK'
TRACK_ORDER_CALLBACK = 'TRACK_ORDER_CALLBACK'
NOTIFICATION_PROBLEM_CALLBACK = 'NOTIFICATION_PROBLEM_CALLBACK'
CHANGE_ORDER_CALLBACK = 'CHANGE_ORDER_CALLBACK'
OTHER_CALLBACK = 'OTHER_CALLBACK'

FORM_CORRECT_CALLBACK = 'FormCorrect'
FORM_INCORRECT_CALLBACK = 'FormIncorrect'

# Telebot constants
CALLBACK_DATA_STR = 'callback_data'